import os

SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL')
SECRET_KEY = os.environ.get('SECRET_KEY')
SQLALCHEMY_TRACK_MODIFICATIONS = False
UPLOAD_FOLDER = os.environ.get('UPLOAD_FOLDER')
MAX_CONTENT_LENGTH = os.environ.get('MAX_CONTENT_LENGTH')
UPLOAD_EXTENSIONS = os.environ.get('UPLOAD_EXTENSIONS')